- job:
    name: testjob
    run: playbooks/testjob.yaml
    parent: base
    
- project:
    region1:
      jobs:
       - testjob:    
           nodeset:
             nodes:
              - name: node
                label: ubuntu-bionic
    region2:
      region1:
      jobs:
       - testjob:
           nodeset: centos76
