- job:
    name: testjob
    run: playbooks/testjob.yaml
    nodeset:
      nodes:
       - name: node
         label: ubuntu-bionic
       - name: node
         label: centos76

- project:
    region1:
      jobs:
        - testjob
        
- project:        
    region2:
      jobs:
        - testjob
