- job:
    name: testjob
    run: playbooks/testjob.yaml
    nodeset:
      nodes:
       - name: node
         label: ubuntu-bionic
- job:
    name: testjob2
    run: playbooks/testjob.yaml
    nodeset:
      nodes:
       - name: node
         label: centos76
- project:
    region1:
      jobs:
        - testjob
    region2:
      jobs:
        - testjob2
