- job:
    name: testjob
    run: playbooks/testjob.yaml
    parent: base
    nodeset:
      nodes:
       - name: node
         label: ubuntu-bionic
       - name: node
         label: centos76

- project:
    region1:
      jobs:
        - testjob
    region2:
      jobs:
       - testjob
