- job:
    name: testjob
    run: playbooks/testjob.yaml
         
- project:
    region1:
      jobs:
        - testjob
        
      nodeset:
        nodes:
         - name: node
           label: ubuntu-bionic
           
    region2:
      jobs:
        - testjob
        
      nodeset:
        nodes:
         - name:node
           label: centos76
