- job:
    name: demoantbuildjob
    run: playbooks/demoantbuildjob.yaml
    parent: base
    nodeset:
      nodes:
        - name: node
          label: ubuntu-bionic
- project:
    check:
      jobs:
        - demoantbuildjob
    gate:
      jobs:
        - demoantbuildjob
