#- job:
 #   name: demoantbuildjob
  #  run: playbooks/demoantbuildjob.yaml
   # parent: base
   0 nodeset:
    #  nodes:
     #   - name: node
          label: ubuntu-bionic
#- project:
 #   check:
  #    jobs:
   #     - demoantbuildjob
    
    #gate:
     # jobs:
      #  - demoantbuildjob
        
- job:
    name: testjob
    run: playbooks/testjob.yaml
    nodeset:
      nodes:
       - name: node
         label: ubuntu-bionic
- job:
    name: testjob2
    run: playbooks/testjob.yaml
    nodeset:
      nodes:
       - name: node_2
         label: zuul-node2
- project:
    userbasedcheck:
      jobs:
        - testjob
    userbasedcheck2:
      jobs:
        - testjob2
        
        
