- job:
    name: testjob
    run: playbooks/testjob.yaml
    nodeset:
      nodes:
       - name: node
         label: ubuntu-bionic
         
- project:
    region1:
      jobs:
        - testjob
      nodeset:
        nodes:
         - name: node
           label: ubuntu-bionic
           
    region2:
      jobs:
        - testjob
      nodeset:
        nodes:
         - name:node
           label: centos76   
