- project:
    region1:
      jobs:
       - name: testjob
         run: playbooks/testjob.yaml
         parent: base
         nodeset:
           nodes:
            - name: node
              label: ubuntu-bionic
    region2:
      jobs:
       - name: testjob
         run: playbooks/testjob.yaml
         parent: base
         nodeset:
           nodes:
            - name: node
              label: ubuntu-bionic
