- nodeset:
    name: ubuntu-bionic
    nodes:
      - name: node
        label: ubuntu-bionic
- nodeset:
    name: centos76
    nodes:
      - name: node2
        label: centos76
- job:
    name: testjob
    run: playbooks/testjob.yaml
    parent: base
    
- project:
    region1:
      jobs:
       - testjob:
           nodeset: ubuntu-bionic
    region2:
      jobs:
       - testjob:
           nodeset: centos76
