- project:
    region1:
      jobs:
       - job:
         name: testjob
         run: playbooks/testjob.yaml			
         nodeset:
           nodes:
            - name: node
              label: ubuntu-bionic
    region1:
      jobs:
       - job:
         name: testjob
         run: playbooks/testjob.yaml			
         nodeset:
           nodes:
            - name: node
              label: ubuntu-bionic
