- hosts: all
  tasks:
    - debug:
        msg: " running with kube user"
    - name: "Deletei the workspace dir before build"
      shell: |
            rm -rf /home/work
      register: clean_output
    - name: Clone git repo
      git:
        repo: https://github.com/wakaleo/game-of-life.git
        dest: /home/work/
      when: clean_output is succeeded
    - name: Build sample project
      shell: |
            /opt/maven/apache-maven-3.5.4/bin/mvn -f /home/work/pom.xml
      register: output
