- hosts: all
  tasks:
    - debug:
        msg: Hello world - test7
    - name: Print the hostname
      shell: hostname
      register: nodename
    - debug:
        msg: node name is {{ nodename.stdout }}
